.TH MComix 1 "January 2016"

.SH NAME
.B MComix
\- GTK Comic Book Viewer

.SH SYNOPSIS
.B mcomix
.RI [ OPTION... "] [" PATH... ]

.SH DESCRIPTION
.B MComix
is a user-friendly, customizable image viewer. It is specifically designed to
handle comic books (both Western comics and manga) and supports a variety of
container formats (including CBR, CBZ, CB7, CBT, LHA and PDF).

.SH OPTIONS
.TP
.BR \-h , " \-\-help"
Display the help text and exit.
.TP
.BR \-s , " \-\-slideshow"
Start the application in slideshow mode.
.TP
.BR \-l , " \-\-library"
Show the library on startup.
.TP
.BR \-v , " \-\-version"
Show the version number and exit.
.PP
.B Viewing modes
.TP
.BR \-f , " \-\-fullscreen"
Start the application in fullscreen mode.
.TP
.BR \-m , " \-\-manga"
Start the application in manga mode.
.TP
.BR \-d , " \-\-double\-page"
Start the application in double page mode.
.PP
.B Zoom modes
.TP
.BR \-b , " \-\-zoom\-best"
Start the application with zoom set to best fit mode.
.TP
.BR \-w , " \-\-zoom\-width"
Start the application with zoom set to fit width.
.TP
.BR \-h , " \-\-zoom\-height"
Start the application with zoom set to fit height.
.PP
The zoom modes are mutually exclusive, and if more than one is specified,
the first will be used.

.SH ARGUMENTS
.TP
.I PATH
The path to one or more files or directories to be opened.

.SH DEPENDENCIES
.SS Required:
.B Python
3.3 or later
.PP
.B PyGObject
3.24 or later, with
.B GTK+ 3
3.22 or later.
.PP
.B PIL
(Python Imaging Library) 1.1.5 or later. Alternatively,
.B Pillow
(a fork of PIL) can be used.
.PP
.BR Distribute " or " Setuptools .
Distribute supersedes Setuptools on most distributions.
.SS Recommended:
.BR unrar ", " rar " or " libunrar
to extract RAR archives.
.PP
.B p7zip
to extract 7Z archives. Note that p7zip might be able to extract RAR archives
as well, but this might require additional software (for example,
.B p7zip-rar
on Debian-like systems), and it might fail to open certain RAR archives,
especially newer ones.
.PP
.B lha
to extract LHA archives.
.PP
.B mupdf
for PDF support.
.PP
.B pysqlite
(if not already built into Python).

.SH BUGS
.PD 0
Please report any bugs to the MComix bug tracker at
.PP
.I http://sourceforge.net/projects/mcomix

.SH CONTACT
.PD 0
The MComix home page is
.PP
.I http://mcomix.sourceforge.net
